
DO $MIG$
DECLARE
  v_seo_id UUID;
BEGIN

-- 1. Trane TruComfort Lakewood Dallas
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/trane-trucomfort-lakewood-dallas', 'Trane TruComfort Lakewood Dallas', 'Trane TruComfort Lakewood Dallas | Truficient', 'Trane TruComfort 20 SEER2 variable-speed installation in Lakewood, Dallas TX 75214. Inverter AC and heat pump for renovated homes near White Rock Lake.', 'https://truficient.com/trane-trucomfort-lakewood-dallas/', 'index, follow', 'Neighborhood + Brand', 'Trane TruComfort Lakewood Dallas', 'Brand - Trane x Lakewood', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/trane-trucomfort-lakewood-dallas/', 'Trane TruComfort for Lakewood, Dallas', 'Lakewood', 'Dallas', 'TX', '75214', 'Brand - Trane x Lakewood', 'Neighborhood + Brand', 'Trane TruComfort Lakewood Dallas | Truficient', 'Trane TruComfort 20 SEER2 variable-speed installation in Lakewood, Dallas TX 75214. Inverter AC and heat pump for renovated homes near White Rock Lake.', 'commercial investigation', 'residential', 'Trane TruComfort Installation', 'Trane 5TTV0X / 5TWV0X', true,
'Trane TruComfort 5TTV0X and 5TWV0X variable-speed installation in Lakewood, Dallas TX 75214. Inverter AC and heat pump for renovated homes near White Rock Lake.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/trane-trucomfort-lakewood-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75214','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8143,'longitude',-96.7227),'geoRadius','5000'),'description','Trane TruComfort 5TTV0X and 5TWV0X variable-speed installation in Lakewood, Dallas TX 75214.','priceRange','$$$'),
true, 'neighborhood_brand', true);

-- 2. Trane WeatherGuard Hail Protection Dallas
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/trane-weatherguard-hail-protection-dallas', 'Trane WeatherGuard Hail Protection Dallas', 'Trane WeatherGuard Hail Protection Dallas | Truficient', 'How Trane WeatherGuard protects your outdoor AC and heat pump from DFW hail damage. Included on all TruComfort models. Call 214-238-4349.', 'https://truficient.com/trane-weatherguard-hail-protection-dallas/', 'index, follow', 'Technical Education', 'Trane WeatherGuard hail protection Dallas', 'Technical Education', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/trane-weatherguard-hail-protection-dallas/', 'Trane WeatherGuard Hail Protection: Why It Matters in Dallas', 'Dallas', 'Dallas', 'TX', '75201', 'Technical Education', 'Technical Education', 'Trane WeatherGuard Hail Protection Dallas | Truficient', 'How Trane WeatherGuard protects your outdoor AC and heat pump from DFW hail damage. Included on all TruComfort models. Call 214-238-4349.', 'informational', 'residential', 'Trane TruComfort Installation', 'Trane 5TTV0X / 5TWV0X', true,
'How Trane WeatherGuard hail protection works, why it matters in Dallas-Fort Worth, and which models include it. Truficient Energy Solutions — Dallas HVAC.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/trane-weatherguard-hail-protection-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75201','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.7767,'longitude',-96.7970),'geoRadius','50000'),'description','How Trane WeatherGuard hail protection works, why it matters in Dallas-Fort Worth, and which models include it.','priceRange','$$$'),
true, 'technical_education', false);

-- 3. R-32 Refrigerant HVAC Dallas
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/r32-refrigerant-hvac-dallas', 'R-32 Refrigerant HVAC Dallas', 'R-32 Refrigerant Explained for Dallas Homeowners | Truficient', 'R-32 vs R-410A vs R-22 vs R-454B — what Dallas homeowners need to know about next-generation HVAC refrigerants. GWP comparison, safety, and what it means.', 'https://truficient.com/r32-refrigerant-hvac-dallas/', 'index, follow', 'Technical Education', 'R-32 refrigerant HVAC Dallas', 'Technical Education', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/r32-refrigerant-hvac-dallas/', 'R-32 Refrigerant: What Dallas Homeowners Need to Know Before Their Next HVAC System', 'Dallas', 'Dallas', 'TX', '75208', 'Technical Education', 'Technical Education', 'R-32 Refrigerant Explained for Dallas Homeowners | Truficient', 'R-32 vs R-410A vs R-22 vs R-454B — what Dallas homeowners need to know about next-generation HVAC refrigerants. GWP comparison, safety, and what it means.', 'informational', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'R-32 refrigerant education for Dallas homeowners. Truficient Energy Solutions explains how R-32 compares to R-410A, R-22, and R-454B.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/r32-refrigerant-hvac-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.7767,'longitude',-96.7970),'geoRadius','40000'),'description','R-32 refrigerant education for Dallas homeowners.','priceRange','$$'),
true, 'technical_education', false);

-- 4. Project: Trane Preston Hollow Dual System
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/project/trane-preston-hollow-dual-system', 'Project: Trane Preston Hollow Dual System', 'Trane TruComfort Dual System Install Preston Hollow | Truficient', 'How Truficient installed two Trane TruComfort variable-speed systems in a Preston Hollow home. Real Dallas project — dual-zone inverter HVAC. Call 214-238-4349.', 'https://truficient.com/project/trane-preston-hollow-dual-system/', 'index, follow', 'Project Showcase', 'Trane TruComfort install Preston Hollow Dallas', 'Brand - Trane x Preston Hollow (Project)', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/project/trane-preston-hollow-dual-system/', 'Project Showcase: Preston Hollow — Dual TruComfort System Installation', 'Preston Hollow', 'Dallas', 'TX', '75225', 'Brand - Trane x Preston Hollow (Project)', 'Project Showcase', 'Trane TruComfort Dual System Install Preston Hollow | Truficient', 'How Truficient installed two Trane TruComfort variable-speed systems in a Preston Hollow home. Real Dallas project — dual-zone inverter HVAC. Call 214-238-4349.', 'commercial investigation', 'residential', 'Trane TruComfort Installation', 'Trane 5TTV0X / 5TWV0X', true,
'Real project: Dual Trane TruComfort variable-speed system installation in a Preston Hollow estate, replacing aging two-stage equipment.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/project/trane-preston-hollow-dual-system/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75225','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8652,'longitude',-96.8005),'geoRadius','5000'),'description','Real project: Dual Trane TruComfort variable-speed system installation in a Preston Hollow estate.','priceRange','$$$'),
true, 'project_showcase', false);

-- 5. Project: Goodman Lake Highlands Ranch Upgrade
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/project/goodman-lake-highlands-ranch-upgrade', 'Project: Goodman Lake Highlands Ranch Upgrade', 'Goodman GXV6SS Install Lake Highlands Ranch Home | Truficient', 'See how Truficient installed a Goodman GXV6SS3610A inverter AC in a 1960s Lake Highlands ranch home. Real Dallas project, real results.', 'https://truficient.com/project/goodman-lake-highlands-ranch-upgrade/', 'index, follow', 'Project Showcase', 'Goodman inverter install Lake Highlands Dallas', 'Brand - Goodman x Lake Highlands (Project)', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/project/goodman-lake-highlands-ranch-upgrade/', 'Project Showcase: Lake Highlands Ranch Home — Single-Stage to Goodman GXV6SS Inverter', 'Lake Highlands', 'Dallas', 'TX', '75231', 'Brand - Goodman x Lake Highlands (Project)', 'Project Showcase', 'Goodman GXV6SS Install Lake Highlands Ranch Home | Truficient', 'See how Truficient installed a Goodman GXV6SS3610A inverter AC in a 1960s Lake Highlands ranch home. Real Dallas project, real results.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Real project: Goodman GXV6SS3610A inverter AC installation in a 1960s Lake Highlands ranch home, replacing an aging single-stage system.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/project/goodman-lake-highlands-ranch-upgrade/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Lake Highlands','addressRegion','TX','postalCode','75231','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8862,'longitude',-96.7284),'geoRadius','6000'),'description','Real project: Goodman GXV6SS3610A inverter AC installation in a 1960s Lake Highlands ranch home.','priceRange','$$'),
true, 'project_showcase', false);

-- 6. Project: Bosch Lower Greenville Quiet Install
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/project/bosch-lower-greenville-quiet-install', 'Project: Bosch Lower Greenville Quiet Install', 'Bosch IDS Quiet Install Lower Greenville Dallas | Truficient', 'Real project: Bosch IDS Premium + BGH96 dual-fuel in a Lower Greenville cottage. Noise reduction was the priority. Call 214-238-4349.', 'https://truficient.com/project/bosch-lower-greenville-quiet-install/', 'index, follow', 'Project Showcase', 'Bosch IDS quiet install Lower Greenville Dallas', 'Brand - Bosch x Lower Greenville (Project)', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/project/bosch-lower-greenville-quiet-install/', 'Project Showcase: Lower Greenville — Bosch IDS Premium Quiet Install in M Streets Cottage', 'Lower Greenville', 'Dallas', 'TX', '75206', 'Brand - Bosch x Lower Greenville (Project)', 'Project Showcase', 'Bosch IDS Quiet Install Lower Greenville Dallas | Truficient', 'Real project: Bosch IDS Premium + BGH96 dual-fuel in a Lower Greenville cottage. Noise reduction was the priority. Call 214-238-4349.', 'commercial investigation', 'residential', 'Bosch Inverter Ducted Installation', 'Bosch IDS Premium', true,
'Real project: Bosch IDS Premium inverter heat pump + BGH96 dual-fuel installation in Lower Greenville / M Streets, Dallas TX. Noise reduction priority.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/project/bosch-lower-greenville-quiet-install/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75206','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8262,'longitude',-96.7680),'geoRadius','5000'),'description','Real project: Bosch IDS Premium inverter heat pump + BGH96 dual-fuel installation in Lower Greenville / M Streets, Dallas TX.','priceRange','$$'),
true, 'project_showcase', false);

END $MIG$;
