
DO $MIG$
DECLARE
  v_seo_id UUID;
BEGIN

-- 1. Goodman Variable Speed Dallas (Brand Pillar)
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-variable-speed-dallas', 'Goodman Variable Speed AC Dallas', 'Goodman Variable Speed AC Dallas | Truficient Installer', 'Goodman GXV6SS and GZV6S inverter systems in Dallas TX. Daikin-built, Texas-made, R-32, lifetime compressor warranty. Call 214-238-4349.', 'https://truficient.com/goodman-variable-speed-dallas/', 'index, follow', 'Brand Pillar', 'Goodman variable speed AC Dallas TX', 'Brand - Goodman', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-variable-speed-dallas/', 'Goodman Variable Speed AC and Heat Pump — Dallas TX Installer Guide', 'Dallas', 'Dallas', 'TX', '75208', 'Brand - Goodman', 'Brand Pillar', 'Goodman Variable Speed AC Dallas | Truficient Installer', 'Goodman GXV6SS and GZV6S inverter systems in Dallas TX. Daikin-built, Texas-made, R-32, lifetime compressor warranty. Call 214-238-4349.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Goodman GXV6SS and GZV6S variable-speed inverter AC and heat pump installation in Dallas TX. Daikin-quality inverter platform, R-32 refrigerant, lifetime compressor warranty.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-variable-speed-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','City','name','Dallas'),'description','Goodman GXV6SS and GZV6S variable-speed inverter AC and heat pump installation in Dallas TX.','priceRange','$$'),
true, 'brand_pillar', false);

-- 2. Goodman Variable Speed Oak Cliff
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-variable-speed-oak-cliff-dallas', 'Goodman Variable Speed Oak Cliff', 'Goodman Variable Speed AC Oak Cliff | Truficient', 'Goodman GXV6SS inverter AC for Oak Cliff Dallas homes. Side-discharge fits tight lots, R-32, lifetime compressor warranty. Call 214-238-4349.', 'https://truficient.com/goodman-variable-speed-oak-cliff-dallas/', 'index, follow', 'Neighborhood + Brand', 'Goodman variable speed AC Oak Cliff Dallas', 'Brand - Goodman x Oak Cliff', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-variable-speed-oak-cliff-dallas/', 'Goodman Variable Speed AC for Oak Cliff Dallas Homes', 'Oak Cliff', 'Dallas', 'TX', '75208', 'Brand - Goodman x Oak Cliff', 'Neighborhood + Brand', 'Goodman Variable Speed AC Oak Cliff | Truficient', 'Goodman GXV6SS inverter AC for Oak Cliff Dallas homes. Side-discharge fits tight lots, R-32, lifetime compressor warranty. Call 214-238-4349.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Goodman GXV6SS variable-speed inverter AC and GZV6S heat pump installation in Oak Cliff, Dallas TX. Daikin-quality inverter for 1940s-1960s bungalows.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-variable-speed-oak-cliff-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Oak Cliff','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.7357,'longitude',-96.8431),'geoRadius','8000'),'description','Goodman GXV6SS variable-speed inverter installation in Oak Cliff, Dallas TX.','priceRange','$$'),
true, 'neighborhood_brand', true);

-- 3. Goodman Variable Speed East Dallas
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-variable-speed-east-dallas', 'Goodman Variable Speed East Dallas', 'Goodman Variable Speed AC East Dallas | Truficient', 'Goodman GXV6SS inverter AC for East Dallas homes. Casa View, Lakewood, Lake Highlands. R-32, lifetime warranty. Call 214-238-4349.', 'https://truficient.com/goodman-variable-speed-east-dallas/', 'index, follow', 'Neighborhood + Brand', 'Goodman variable speed AC East Dallas', 'Brand - Goodman x East Dallas', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-variable-speed-east-dallas/', 'Goodman Variable Speed AC for East Dallas Homes', 'East Dallas', 'Dallas', 'TX', '75218', 'Brand - Goodman x East Dallas', 'Neighborhood + Brand', 'Goodman Variable Speed AC East Dallas | Truficient', 'Goodman GXV6SS inverter AC for East Dallas homes. Casa View, Lakewood, Lake Highlands. R-32, lifetime warranty. Call 214-238-4349.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Goodman GXV6SS variable-speed inverter installation in East Dallas — Casa View, Lakewood, Lake Highlands.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-variable-speed-east-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','East Dallas','addressRegion','TX','postalCode','75218','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8175,'longitude',-96.7136),'geoRadius','10000'),'description','Goodman GXV6SS variable-speed inverter installation in East Dallas.','priceRange','$$'),
true, 'neighborhood_brand', true);

-- 4. Goodman Variable Speed Lake Highlands
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-variable-speed-lake-highlands-dallas', 'Goodman Variable Speed Lake Highlands', 'Goodman Variable Speed AC Lake Highlands | Truficient', 'Goodman GXV6SS inverter AC for Lake Highlands Dallas. 1960s-1970s home specialist. R-32, lifetime compressor warranty. Call 214-238-4349.', 'https://truficient.com/goodman-variable-speed-lake-highlands-dallas/', 'index, follow', 'Neighborhood + Brand', 'Goodman variable speed AC Lake Highlands Dallas', 'Brand - Goodman x Lake Highlands', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-variable-speed-lake-highlands-dallas/', 'Goodman Variable Speed AC for Lake Highlands Dallas', 'Lake Highlands', 'Dallas', 'TX', '75231', 'Brand - Goodman x Lake Highlands', 'Neighborhood + Brand', 'Goodman Variable Speed AC Lake Highlands | Truficient', 'Goodman GXV6SS inverter AC for Lake Highlands Dallas. 1960s-1970s home specialist. R-32, lifetime compressor warranty. Call 214-238-4349.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Goodman GXV6SS variable-speed inverter AC installation for Lake Highlands Dallas. 1960s-1970s ranch and two-story specialist.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-variable-speed-lake-highlands-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Lake Highlands','addressRegion','TX','postalCode','75231','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.8862,'longitude',-96.7284),'geoRadius','6000'),'description','Goodman GXV6SS variable-speed inverter AC installation for Lake Highlands Dallas.','priceRange','$$'),
true, 'neighborhood_brand', true);

-- 5. Goodman Variable Speed Bishop Arts
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-variable-speed-bishop-arts-dallas', 'Goodman Variable Speed Bishop Arts', 'Goodman Variable Speed AC Bishop Arts | Truficient', 'Goodman GXV6SS and GZV6S inverter systems for Bishop Arts Dallas. Heat pump upgrades for historic bungalows. Call 214-238-4349.', 'https://truficient.com/goodman-variable-speed-bishop-arts-dallas/', 'index, follow', 'Neighborhood + Brand', 'Goodman inverter AC Bishop Arts Dallas', 'Brand - Goodman x Bishop Arts', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-variable-speed-bishop-arts-dallas/', 'Goodman Variable Speed AC and Heat Pump — Bishop Arts District, Dallas', 'Bishop Arts', 'Dallas', 'TX', '75208', 'Brand - Goodman x Bishop Arts', 'Neighborhood + Brand', 'Goodman Variable Speed AC Bishop Arts | Truficient', 'Goodman GXV6SS and GZV6S inverter systems for Bishop Arts Dallas. Heat pump upgrades for historic bungalows. Call 214-238-4349.', 'commercial investigation', 'residential', 'Goodman Variable Speed Installation', 'Goodman GXV6SS / GZV6S', true,
'Goodman GXV6SS and GZV6S variable-speed inverter installation in Bishop Arts District, Dallas TX. Heat pump conversions for historic bungalows.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-variable-speed-bishop-arts-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Bishop Arts','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.7438,'longitude',-96.8268),'geoRadius','5000'),'description','Goodman variable-speed inverter installation in Bishop Arts District, Dallas TX.','priceRange','$$'),
true, 'neighborhood_brand', true);

-- 6. Goodman GZV6S Heat Pump (Product Detail)
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/goodman-gzv6s-heat-pump-dallas', 'Goodman GZV6S Heat Pump Dallas', 'Goodman GZV6S Heat Pump Dallas | Truficient Installer', 'Goodman GZV6S inverter heat pump in Dallas TX. Variable-speed, R-32, dual-fuel or all-electric. Daikin platform. Call 214-238-4349.', 'https://truficient.com/goodman-gzv6s-heat-pump-dallas/', 'index, follow', 'Product Detail', 'Goodman GZV6S heat pump Dallas TX', 'Brand - Goodman', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/goodman-gzv6s-heat-pump-dallas/', 'Goodman GZV6S Inverter Heat Pump — Dallas TX Installation Guide', 'Dallas', 'Dallas', 'TX', '75208', 'Brand - Goodman', 'Product Detail', 'Goodman GZV6S Heat Pump Dallas | Truficient Installer', 'Goodman GZV6S inverter heat pump in Dallas TX. Variable-speed, R-32, dual-fuel or all-electric. Daikin platform. Call 214-238-4349.', 'commercial investigation', 'residential', 'Heat Pump Installation', 'Goodman GZV6S', true,
'Goodman GZV6S inverter heat pump installation in Dallas TX. Variable-speed, R-32, dual-fuel and all-electric configurations.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/goodman-gzv6s-heat-pump-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','City','name','Dallas'),'description','Goodman GZV6S inverter heat pump installation in Dallas TX.','priceRange','$$'),
true, 'product_detail', false);

-- 7. Bosch Inverter Ducted Dallas (Brand Pillar)
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/bosch-inverter-ducted-dallas', 'Bosch Inverter Ducted Dallas', 'Bosch Inverter Ducted HVAC Dallas | Truficient', 'Bosch IDS inverter ducted heat pumps and dual-fuel systems in Dallas TX. Ultra-quiet, R-454B, BGH96 furnace pairing. Call 214-238-4349.', 'https://truficient.com/bosch-inverter-ducted-dallas/', 'index, follow', 'Brand Pillar', 'Bosch inverter ducted HVAC Dallas TX', 'Brand - Bosch', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/bosch-inverter-ducted-dallas/', 'Bosch Inverter Ducted Heat Pump and Dual-Fuel Systems — Dallas TX', 'Dallas', 'Dallas', 'TX', '75208', 'Brand - Bosch', 'Brand Pillar', 'Bosch Inverter Ducted HVAC Dallas | Truficient', 'Bosch IDS inverter ducted heat pumps and dual-fuel systems in Dallas TX. Ultra-quiet, R-454B, BGH96 furnace pairing. Call 214-238-4349.', 'commercial investigation', 'residential', 'Bosch IDS Installation', 'Bosch IDS + BGH96', true,
'Bosch IDS inverter ducted heat pump and dual-fuel HVAC installation in Dallas TX. European-engineered, ultra-quiet, R-454B, BGH96 96% furnace pairing.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/bosch-inverter-ducted-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','City','name','Dallas'),'description','Bosch IDS inverter ducted heat pump and dual-fuel HVAC installation in Dallas TX.','priceRange','$$'),
true, 'brand_pillar', false);

-- 8. Bosch Inverter Ducted Oak Cliff
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/bosch-inverter-ducted-oak-cliff-dallas', 'Bosch Inverter Ducted Oak Cliff', 'Bosch Inverter Ducted AC Oak Cliff Dallas | Truficient', 'Bosch IDS inverter ducted and BGH96 dual-fuel for Oak Cliff Dallas homes. Ultra-quiet, R-454B. Call 214-238-4349.', 'https://truficient.com/bosch-inverter-ducted-oak-cliff-dallas/', 'index, follow', 'Neighborhood + Brand', 'Bosch inverter ducted Oak Cliff Dallas', 'Brand - Bosch x Oak Cliff', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/bosch-inverter-ducted-oak-cliff-dallas/', 'Bosch Inverter Ducted for Oak Cliff Dallas — The Quiet, Efficient Alternative', 'Oak Cliff', 'Dallas', 'TX', '75208', 'Brand - Bosch x Oak Cliff', 'Neighborhood + Brand', 'Bosch Inverter Ducted AC Oak Cliff Dallas | Truficient', 'Bosch IDS inverter ducted and BGH96 dual-fuel for Oak Cliff Dallas homes. Ultra-quiet, R-454B. Call 214-238-4349.', 'commercial investigation', 'residential', 'Bosch IDS Installation', 'Bosch IDS + BGH96', true,
'Bosch IDS inverter ducted and BGH96 dual-fuel installation in Oak Cliff, Dallas TX. Ultra-quiet for close-neighbor lots, R-454B refrigerant.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/bosch-inverter-ducted-oak-cliff-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Oak Cliff','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','GeoCircle','geoMidpoint',jsonb_build_object('@type','GeoCoordinates','latitude',32.7357,'longitude',-96.8431),'geoRadius','8000'),'description','Bosch IDS inverter ducted and BGH96 dual-fuel installation in Oak Cliff, Dallas TX.','priceRange','$$'),
true, 'neighborhood_brand', true);

-- 9. Bosch Dual-Fuel Heat Pump (Education)
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/bosch-dual-fuel-heat-pump-dallas', 'Bosch Dual-Fuel Heat Pump Dallas', 'Bosch Dual-Fuel Heat Pump Dallas | Truficient', 'How Bosch IDS inverter heat pump + BGH96 furnace dual-fuel works in Dallas TX. The smartest path off natural gas. Call 214-238-4349.', 'https://truficient.com/bosch-dual-fuel-heat-pump-dallas/', 'index, follow', 'Education', 'Bosch dual fuel heat pump Dallas TX', 'Brand - Bosch', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/bosch-dual-fuel-heat-pump-dallas/', 'Bosch Dual-Fuel Heat Pump: How the IDS + BGH96 Works in Dallas', 'Dallas', 'Dallas', 'TX', '75208', 'Brand - Bosch', 'Education', 'Bosch Dual-Fuel Heat Pump Dallas | Truficient', 'How Bosch IDS inverter heat pump + BGH96 furnace dual-fuel works in Dallas TX. The smartest path off natural gas. Call 214-238-4349.', 'commercial investigation', 'residential', 'Dual-Fuel Heat Pump Installation', 'Bosch IDS + BGH96', true,
'Bosch IDS + BGH96 dual-fuel system installation in Dallas TX. The most integrated dual-fuel design — engineered as a matched pair.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/bosch-dual-fuel-heat-pump-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','City','name','Dallas'),'description','Bosch IDS + BGH96 dual-fuel system installation in Dallas TX.','priceRange','$$'),
true, 'education', false);

-- 10. Best Dual-Fuel Heat Pump Dallas (Comparison)
INSERT INTO public.page_seo (page_path, page_name, meta_title, meta_description, canonical_url, robots, page_type, target_keyword, cluster, index_status, schema_applied, last_content_update)
VALUES ('/best-dual-fuel-heat-pump-dallas', 'Best Dual-Fuel Heat Pump Dallas', 'Best Dual-Fuel Heat Pump Dallas TX | Truficient', 'Compare Bosch IDS + BGH96, Goodman GZV6S + GRVT96, and Trane 5TWV0X + S9V2U dual-fuel heat pump systems for Dallas. Call 214-238-4349.', 'https://truficient.com/best-dual-fuel-heat-pump-dallas/', 'index, follow', 'Comparison', 'best dual fuel heat pump Dallas TX', 'Cross-Brand Comparison', 'pending', true, now())
RETURNING id INTO v_seo_id;
INSERT INTO public.seo_location_pages (page_seo_id, url_slug, h1_title, neighborhood, city, state, zip_code, cluster, page_type, meta_title, meta_description, search_intent, audience, primary_service, recommended_system, schema_enabled, schema_description, schema_json, published, template, add_to_service_areas_hub)
VALUES (v_seo_id, '/best-dual-fuel-heat-pump-dallas/', 'Best Dual-Fuel Heat Pump System for Dallas TX — Three Inverter Options Compared', 'Dallas', 'Dallas', 'TX', '75208', 'Cross-Brand Comparison', 'Comparison', 'Best Dual-Fuel Heat Pump Dallas TX | Truficient', 'Compare Bosch IDS + BGH96, Goodman GZV6S + GRVT96, and Trane 5TWV0X + S9V2U dual-fuel heat pump systems for Dallas. Call 214-238-4349.', 'commercial investigation', 'residential', 'Dual-Fuel Heat Pump Installation', 'Bosch / Goodman / Trane', true,
'Compare the three best dual-fuel heat pump systems for Dallas TX: Bosch IDS + BGH96, Goodman GZV6S + GRVT96, and Trane 5TWV0X + S9V2U.',
jsonb_build_object('@context','https://schema.org','@type','HVACBusiness','name','Truficient Energy Solutions','url','https://truficient.com/best-dual-fuel-heat-pump-dallas/','telephone','214-238-4349','address',jsonb_build_object('@type','PostalAddress','addressLocality','Dallas','addressRegion','TX','postalCode','75208','addressCountry','US'),'areaServed',jsonb_build_object('@type','City','name','Dallas'),'description','Compare the three best dual-fuel heat pump systems for Dallas TX: Bosch, Goodman, and Trane.','priceRange','$$-$$$'),
true, 'comparison', false);

END $MIG$;
