// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { TENANT_SCOPED_TABLES } from './tenantScopedTables';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ============================================================================
// Multi-tenancy: auto-attach tenant_id on every insert/upsert.
//
// Every tenant-scoped table (see tenantScopedTables.ts, kept in sync with
// supabase/migrations/20260803180000_multi_tenancy.sql) requires a NOT NULL
// tenant_id column and is guarded by RLS comparing it to
// public.get_current_tenant_id(). SELECT/UPDATE/DELETE need no client-side
// change — RLS enforces those transparently. INSERT/UPSERT create rows that
// don't have a tenant_id yet, so this patches `supabase.from(...)` itself:
// every existing and future call site (`supabase.from('crm_customers').insert(...)`)
// gets tenant_id injected automatically, with zero changes at the call site.
//
// If a caller explicitly sets tenant_id on the row they pass in, that value
// wins — this only fills in the gap, it never overrides an explicit value.
// ============================================================================

let cachedTenantId: string | null = null;
let pendingFetch: Promise<string | null> | null = null;

async function fetchCurrentTenantId(): Promise<string | null> {
  // Cast: `get_current_tenant_id` is defined in the multi-tenancy migration
  // but types.ts hasn't been regenerated against a live project yet (see
  // README.md "Setup"). Drop this cast once real types are pulled.
  const { data, error } = await (supabase.rpc as any)('get_current_tenant_id');
  if (error) {
    console.error('[tenant] failed to resolve current tenant_id:', error.message);
    return null;
  }
  return data ?? null;
}

function refreshTenantId(): Promise<string | null> {
  cachedTenantId = null;
  pendingFetch = fetchCurrentTenantId().then((id) => {
    cachedTenantId = id;
    return id;
  });
  return pendingFetch;
}

async function ensureTenantId(): Promise<string | null> {
  if (cachedTenantId) return cachedTenantId;
  if (pendingFetch) return pendingFetch;
  return refreshTenantId();
}

supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_OUT') {
    cachedTenantId = null;
    pendingFetch = null;
  } else if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED' || event === 'INITIAL_SESSION') {
    void refreshTenantId();
  }
});

// Warm the cache immediately if a session already exists (e.g. page reload).
void supabase.auth.getSession().then(({ data }) => {
  if (data.session) void ensureTenantId();
});

function withTenantId<T extends Record<string, unknown>>(row: T): T {
  if (cachedTenantId == null) {
    console.warn(
      '[tenant] inserting before tenant_id was resolved — this row will fail its NOT NULL/RLS check. ' +
      'This should only happen if an insert fires before auth finishes initializing.',
    );
    return row;
  }
  return 'tenant_id' in row && row.tenant_id != null ? row : { ...row, tenant_id: cachedTenantId };
}

type AnyRow = Record<string, unknown>;
type Rows = AnyRow | AnyRow[];

function withTenantIds(values: Rows): Rows {
  return Array.isArray(values) ? values.map(withTenantId) : withTenantId(values);
}

const rawFrom = supabase.from.bind(supabase);

// @ts-expect-error -- intentionally widening supabase.from's return type so we
// can patch insert/upsert on tenant-scoped tables; all other methods (select,
// update, delete, chaining) pass through to the untouched query builder.
supabase.from = (table: string) => {
  const builder: any = rawFrom(table as never);
  if (!TENANT_SCOPED_TABLES.has(table)) return builder;

  const originalInsert = builder.insert.bind(builder);
  const originalUpsert = builder.upsert.bind(builder);

  builder.insert = (values: Rows, options?: unknown) => originalInsert(withTenantIds(values), options);
  builder.upsert = (values: Rows, options?: unknown) => originalUpsert(withTenantIds(values), options);

  return builder;
};

/** For code (e.g. forms, edge-function calls) that needs the current tenant_id directly. */
export async function getCurrentTenantId(): Promise<string | null> {
  return ensureTenantId();
}

/**
 * Use instead of `supabase.channel(name)` for realtime subscriptions.
 *
 * React 18 StrictMode double-invokes effects in dev: the first mount's
 * cleanup (`removeChannel`) can still be in flight when the second mount
 * tries to `.subscribe()` a channel with the same name, throwing "cannot
 * add postgres_changes callbacks ... after subscribe()" because
 * supabase-js reuses the existing channel instance for that topic. This
 * clears out any stale channel with the same name first.
 */
export function freshChannel(name: string) {
  supabase.getChannels()
    .filter((c) => c.topic === `realtime:${name}`)
    .forEach((c) => supabase.removeChannel(c));
  return supabase.channel(name);
}
