import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { AdminLayout } from '@/components/admin/AdminLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { toast } from 'sonner';
import { Plus, Eye, Pencil, Copy, Trash2, FileText, Search, Tag, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { format } from 'date-fns';
import { Link, useNavigate } from 'react-router-dom';

type EstimateStatus = 'draft' | 'sent' | 'accepted' | 'declined' | 'expired';

interface Estimate {
  id: string;
  estimate_number: string;
  title: string | null;
  tags: string[] | null;
  customer_name: string;
  customer_email: string | null;
  customer_phone: string | null;
  job_type: string;
  status: EstimateStatus;
  grand_total: number;
  created_at: string;
  updated_at: string;
}

const STATUS_OPTIONS: { value: EstimateStatus | 'all'; label: string }[] = [
  { value: 'all', label: 'All Statuses' },
  { value: 'draft', label: 'Draft' },
  { value: 'sent', label: 'Sent' },
  { value: 'accepted', label: 'Accepted' },
  { value: 'declined', label: 'Declined' },
  { value: 'expired', label: 'Expired' },
];

const STATUS_COLORS: Record<EstimateStatus, string> = {
  draft: 'bg-gray-100 text-gray-800',
  sent: 'bg-blue-100 text-blue-800',
  accepted: 'bg-green-100 text-green-800',
  declined: 'bg-red-100 text-red-800',
  expired: 'bg-amber-100 text-amber-800',
};

const JOB_TYPE_LABELS: Record<string, string> = {
  residential_new: 'Residential - New',
  residential_replacement: 'Residential - Replacement',
  commercial_new: 'Commercial - New',
  commercial_replacement: 'Commercial - Replacement',
  maintenance: 'Maintenance',
  repair: 'Repair',
};

const Estimates = () => {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [statusFilter, setStatusFilter] = useState<EstimateStatus | 'all'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [tagFilter, setTagFilter] = useState<string | null>(null);

  // Fetch estimates
  const { data: estimates = [], isLoading } = useQuery({
    queryKey: ['estimates', statusFilter],
    queryFn: async () => {
      let query = supabase
        .from('estimates')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (statusFilter !== 'all') {
        query = query.eq('status', statusFilter);
      }
      
      const { data, error } = await query;
      if (error) throw error;
      return data as Estimate[];
    },
  });

  // Clone mutation
  const cloneMutation = useMutation({
    mutationFn: async (id: string) => {
      // First get the estimate and its line items
      const { data: estimate, error: estimateError } = await supabase
        .from('estimates')
        .select('*')
        .eq('id', id)
        .single();
      
      if (estimateError) throw estimateError;

      const { data: lineItems, error: lineItemsError } = await supabase
        .from('estimate_line_items')
        .select('*')
        .eq('estimate_id', id);
      
      if (lineItemsError) throw lineItemsError;

      // Create new estimate (estimate_number will be auto-generated)
      const { data: newEstimate, error: createError } = await supabase
        .from('estimates')
        .insert({
          estimate_number: '', // Will be auto-generated by trigger
          customer_name: estimate.customer_name + ' (Copy)',
          customer_email: estimate.customer_email,
          customer_phone: estimate.customer_phone,
          customer_address: estimate.customer_address,
          job_type: estimate.job_type,
          heating_type: estimate.heating_type,
          job_notes: estimate.job_notes,
          status: 'draft',
          profit_margin: estimate.profit_margin,
          tax_rate: estimate.tax_rate,
          title: estimate.title ? estimate.title + ' (Copy)' : null,
          tags: estimate.tags,
        })
        .select()
        .single();
      
      if (createError) throw createError;

      // Clone line items
      if (lineItems && lineItems.length > 0) {
        const newLineItems = lineItems.map(item => ({
          estimate_id: newEstimate.id,
          item_type: item.item_type,
          name: item.name,
          description: item.description,
          material_id: item.material_id,
          labor_rate_id: item.labor_rate_id,
          admin_cost_id: item.admin_cost_id,
          equipment_system_id: item.equipment_system_id,
          quantity: item.quantity,
          unit: item.unit,
          unit_cost: item.unit_cost,
          sort_order: item.sort_order,
          section: item.section,
        }));

        const { error: insertError } = await supabase
          .from('estimate_line_items')
          .insert(newLineItems);
        
        if (insertError) throw insertError;
      }

      return newEstimate;
    },
    onSuccess: (newEstimate) => {
      queryClient.invalidateQueries({ queryKey: ['estimates'] });
      toast.success('Estimate cloned successfully');
      navigate(`/admin/estimates/${newEstimate.id}`);
    },
    onError: (error) => {
      toast.error('Failed to clone estimate: ' + error.message);
    },
  });

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('estimates')
        .delete()
        .eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['estimates'] });
      toast.success('Estimate deleted successfully');
    },
    onError: (error) => {
      toast.error('Failed to delete estimate: ' + error.message);
    },
  });

  const handleDelete = (id: string, estimateNumber: string) => {
    if (confirm(`Are you sure you want to delete estimate ${estimateNumber}?`)) {
      deleteMutation.mutate(id);
    }
  };

  // Collect all unique tags for filter
  const allTags = Array.from(new Set(estimates.flatMap(e => e.tags || []))).sort();

  // Filter by search and tag
  const filteredEstimates = estimates.filter(estimate => {
    const matchesSearch = estimate.customer_name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      estimate.estimate_number.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (estimate.customer_email && estimate.customer_email.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (estimate.title && estimate.title.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesTag = !tagFilter || (estimate.tags && estimate.tags.includes(tagFilter));
    return matchesSearch && matchesTag;
  });

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  return (
    <AdminLayout title="Estimates">
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-2xl font-bold text-foreground">Project Estimates</h1>
              <p className="text-muted-foreground">Create and manage HVAC project estimates</p>
            </div>
          </div>
          <Button asChild>
            <Link to="/admin/estimates/new">
              <Plus className="h-4 w-4 mr-2" />
              New Estimate
            </Link>
          </Button>
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search by customer name, email, or estimate #..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
           <Select value={statusFilter} onValueChange={(v) => setStatusFilter(v as EstimateStatus | 'all')}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              {STATUS_OPTIONS.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {allTags.length > 0 && (
            <Select value={tagFilter || 'all'} onValueChange={(v) => setTagFilter(v === 'all' ? null : v)}>
              <SelectTrigger className="w-[180px]">
                <Tag className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Filter by tag" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Tags</SelectItem>
                {allTags.map((tag) => (
                  <SelectItem key={tag} value={tag}>{tag}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}
        </div>

        {/* Table */}
        {isLoading ? (
          <div className="text-center py-8 text-muted-foreground">Loading...</div>
        ) : filteredEstimates.length === 0 ? (
          <div className="text-center py-12 text-muted-foreground">
            <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
            <p className="text-lg font-medium">No estimates found</p>
            <p className="text-sm">
              {searchQuery || statusFilter !== 'all' 
                ? 'Try adjusting your filters' 
                : 'Click "New Estimate" to create your first estimate'}
            </p>
          </div>
        ) : (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Estimate #</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Job Type</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Total</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredEstimates.map((estimate) => (
                  <TableRow key={estimate.id}>
                    <TableCell className="font-mono font-medium text-sm">
                      {estimate.estimate_number}
                    </TableCell>
                    <TableCell>
                      <div>
                        <div className="font-medium">{estimate.title || <span className="text-muted-foreground italic">Untitled</span>}</div>
                        {estimate.tags && estimate.tags.length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-1">
                            {estimate.tags.map((tag, i) => (
                              <Badge key={i} variant="secondary" className="text-[10px] px-1.5 py-0 cursor-pointer" onClick={() => setTagFilter(tag)}>
                                {tag}
                              </Badge>
                            ))}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <div>
                        <div className="font-medium">{estimate.customer_name}</div>
                        {estimate.customer_email && (
                          <div className="text-sm text-muted-foreground">{estimate.customer_email}</div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      {JOB_TYPE_LABELS[estimate.job_type] || estimate.job_type}
                    </TableCell>
                    <TableCell>
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium capitalize ${STATUS_COLORS[estimate.status]}`}>
                        {estimate.status}
                      </span>
                    </TableCell>
                    <TableCell className="text-right font-mono font-semibold">
                      {formatCurrency(estimate.grand_total)}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {format(new Date(estimate.created_at), 'MMM d, yyyy')}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button
                          variant="ghost"
                          size="icon"
                          asChild
                          title="View"
                        >
                          <Link to={`/admin/estimates/${estimate.id}`}>
                            <Eye className="h-4 w-4" />
                          </Link>
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          asChild
                          title="Edit"
                        >
                          <Link to={`/admin/estimates/${estimate.id}`}>
                            <Pencil className="h-4 w-4" />
                          </Link>
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => cloneMutation.mutate(estimate.id)}
                          disabled={cloneMutation.isPending}
                          title="Clone"
                        >
                          <Copy className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleDelete(estimate.id, estimate.estimate_number)}
                          className="text-destructive hover:text-destructive"
                          title="Delete"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </div>
    </AdminLayout>
  );
};

export default Estimates;
